### ISSUE TITLE
Improve File Encryption/Decryption Integration in the GUI

### ISSUE THREAD

**Issue by marcos-morar** [saturneric/GpgFrontend#193]
In many GPG-related GUIs like GPA, Gpg4Usb, and Kleopatra, encrypting and decrypting files is a straightforward process: select a public key, choose a file, click encrypt—done.

However, in GpgFrontend, the File Panel can be confusing for users, especially those unfamiliar with its workflow. When opening the File Panel, users expect to see their files immediately, but instead, they are prompted to select a folder first. This leads to confusion, as many assume that files are missing or not being displayed.

Additionally, the encryption process itself is more complex than necessary. For example:

- Users must select a file rather than double-clicking it, which is not intuitive.

- The overall process requires extra steps that make it harder for new users to grasp.

To improve usability, please consider simplifying file encryption/decryption to be more in line with other GPG frontends—allowing users to quickly select a file and encrypt/decrypt it with minimal steps.

Thank you!

**Comment by saturneric** [comment]
The single-file operation functions you mentioned were available in gpg4usb in the past, but I removed them years ago. The current FilePanel approach provides a convenient way to handle files, if it supports multi-selection and batch operations (such as encrypting or signing multiple files or directories at once). However, batch operations were not supported for a long time and have recently been implemented in the develop branch (nightly build).

I will consider reintroducing the single-file operation functions.

**Comment by Achim16** [comment]
The chosen approach is indeed powerful but indeed not intuitive, even an advanced user who has not used the program for a while
sometimes thinks 'wait, how again can I encrypt a binary file ?? Ah, I recall, it's the file panel'.  Don't know how often I tried to just open a binary file in the tab ... 

File panel or not has pros and cons.
More importantly, the usage of "file" in the pop-up help is confusing. "New" "opens a new file" but what is meant is "tab" or "message". Same for "open" which opens an existing (text) file, whilst the file panel adresses binary files - means files in general.

![Image](https://github.com/user-attachments/assets/10a33e82-8e95-47f1-9508-7e5d32c2cfd2)

Personally I found the layout of gpg4usb options more intuitive, regardless of whether 'encrypt file' then opens a multi-file panel or not (or have both, single file, multi-file menu entries) :

![Image](https://github.com/user-attachments/assets/0e7bd791-2dd8-46bc-996d-1afc719009c0)

great program, I'm sure it will evolve further

**Comment by saturneric** [comment]
Thanks, I'll work on it.

**Comment by BlazarKnight** [comment]
let's just add a way to use a different toolbar in settings, is this a good solution?

**Comment by marcos-morar** [comment]
**Possible Workarounds for the File Panel:**

**Allow File Selection in the File Panel:**

- When the user clicks the File Panel button, the app should allow them to select a file instead of just a folder.

- Upon clicking "OK," the file panel should open in the corresponding folder, with the selected file highlighted in the tab.

OR

**Pin the File Panel to the Main Window:**

- Pin the file panel tab to the main window, where, by default, it displays mounted devices.

- Users should navigate through the panel to select the desired file.

- The app could remember the last used folder and open it automatically the next time the user starts the application.

**Comment by saturneric** [comment]
> **Possible Workarounds for the File Panel:**
> 
> **Allow File Selection in the File Panel:**
> 
>     * When the user clicks the File Panel button, the app should allow them to select a file instead of just a folder.
> 
>     * Upon clicking "OK," the file panel should open in the corresponding folder, with the selected file highlighted in the tab.
> 
> 
> OR
> 
> **Pin the File Panel to the Main Window:**
> 
>     * Pin the file panel tab to the main window, where, by default, it displays mounted devices.
> 
>     * Users should navigate through the panel to select the desired file.
> 
>     * The app could remember the last used folder and open it automatically the next time the user starts the application.

Thanks for the great suggestions! I’ve reviewed both proposed directions and agree they align well with our goals. Based on my current design (see screenshot), I plan to transition from a text-based model to a workspace-based model.

<img width="796" alt="Image" src="https://github.com/user-attachments/assets/7c6cec17-f27f-40c3-9eb3-848b0431defc" />

**Comment by saturneric** [comment]
Changes mentioned above are applied. From v2.1.8, I think there will be less confusing situations.

**Comment by saturneric** [comment]
@Achim16 I've fixed this. This issue happened on Windows. You may retry with the latest nightly build.

**Comment by Achim16** [comment]
Thanks, downloaded GpgFrontend-28f82dd7-x86_64.zip. However no change, behaviour still the same as described above, sorry.
Off Topic remark - Usually I test with by copying "db" dir over from regular GPGFrontend folder, this time I wanted to do completely
from scratch (after reboot of course) with a newly generated key - program says "The current Gnupg version too low ..."

**Comment by saturneric** [comment]
That's a bug. I'm currently fixing this.
